Import Packages

In [16]:
import pandas as pd
import numpy as np
import warnings

from datetime import datetime, timedelta
from IPython.display import display

warnings.filterwarnings("ignore")

Read Data with Pandas

In [17]:
pop_data_raw = pd.read_csv("Pop_Data_Raw.csv")#read input data

pop_transposed = pop_data_raw.transpose()#flip dataframe

final_table = pop_transposed.iloc[2:3,0:12]#create data frame header columns

count_start = 0
count_end = 12
for i in range(9):
    transposed_country = pop_transposed.iloc[4:, count_start: count_end]
    transposed_country.columns = range(transposed_country.columns.size)
    final_table = pd.concat([final_table, transposed_country], axis=0, ignore_index=True)
    count_start = count_end 
    count_end = count_end + 12

final_table.head(1)

,0,1,2,3,4,5,6,7,8,9,10,11
0,Population ages 15-64 (% of total population),Population ages 65 and above (% of total popul...,Population growth (annual %),"Population, female (% of total population)","Population, male (% of total population)",Rural population (% of total population),Rural population growth (annual %),Urban population (% of total population),Urban population growth (annual %),"Life expectancy at birth, total (years)","Life expectancy at birth, male (years)","Life expectancy at birth, female (years)"

Create Population Dataframe

In [18]:

final_table.columns=["Population_15To64_Percent", "Population_65andUp_Percent","Population_Growth_Percent", "Population_Female_Percent", "Population_Male_Percent", "Rural_Population_Percent", "Rural_Population_Growth_Percent", "Urban_Population_Percent", "Urban_Population_Growth_Percent", "Life_Exp_Birth_Total_Yr", "Life_Exp_Birth_Male_Yr", "Life_Exp_Birth_Female_Yr"]

Add Country Name and Year

In [19]:

count = 5
iterator = 0;
countries = ["Canada", "USA", "Mexico", "Burundi", "Chad", "Niger", "Bolivia", "Philippines", "Indonesia"]

country_year = pd.DataFrame(columns=["Country","Year"])

pop_data = {}
pop_data["Country"] = "Blank"
pop_data["Year"] = 0
  
country_year = country_year.append(pd.DataFrame([pop_data]), ignore_index=True)


for i in range(144):
    if count>20:
        count = 5
        iterator = iterator + 1

    pop_data["Year"] = 2000+count
    pop_data["Country"] = countries[iterator]
    count = count + 1
    country_year = country_year.append(pd.DataFrame([pop_data]), ignore_index=True)

display(country_year.tail(5))

       Country  Year
140  Indonesia  2016
141  Indonesia  2017
142  Indonesia  2018
143  Indonesia  2019
144  Indonesia  2020

Join Country_Year with Final_Table

In [20]:
final_table = pd.concat([country_year, final_table], axis=1)
display(final_table.tail(20))

,Country,Year,Population_15To64_Percent,Population_65andUp_Percent,Population_Growth_Percent,Population_Female_Percent,Population_Male_Percent,Rural_Population_Percent,Rural_Population_Growth_Percent,Urban_Population_Percent,Urban_Population_Growth_Percent,Life_Exp_Birth_Total_Yr,Life_Exp_Birth_Male_Yr,Life_Exp_Birth_Female_Yr
125,Philippines,2017,63.594895,4.937097,1.445278,49.721566,50.278434,53.318,1.057793,46.682,1.889689,70.952,66.971,75.268
126,Philippines,2018,63.914391,5.122569,1.395965,49.741657,50.258343,53.093,0.973077,46.907,1.876791,71.095,67.123,75.387
127,Philippines,2019,64.209123,5.314996,1.364496,49.76159,50.23841,52.851,0.90765,47.149,1.879085,71.231,67.263,75.505
128,Philippines,2020,64.4456728195355,5.51164864430335,1.34542996462104,49.7825514321199,50.2174485678801,52.592,0.854167721331776,47.408,1.89324969217441,..,..,..
129,Indonesia,2005,65.31797,4.800765,1.336305,49.802177,50.197823,54.058,-0.119983,45.942,3.077465,67.334,65.579,69.107
130,Indonesia,2006,65.610642,4.868223,1.329582,49.762018,50.237982,53.262,-0.15386,46.738,3.047363,67.717,65.899,69.565
131,Indonesia,2007,65.836215,4.918852,1.323834,49.720245,50.279755,52.465,-0.183852,47.535,3.014709,68.105,66.228,70.025
132,Indonesia,2008,66.003012,4.952434,1.323331,49.680785,50.319215,51.665,-0.21324,48.335,2.992295,68.485,66.554,70.474
133,Indonesia,2009,66.119766,4.967382,1.329217,49.648484,50.351516,50.866,-0.229367,49.134,2.96875,68.853,66.872,70.905
134,Indonesia,2010,66.209384,4.962514,1.337782,49.626442,50.373558,50.086,-0.207537,49.914,2.912809,69.205,67.182,71.311
135,Indonesia,2011,66.431675,5.044132,1.347904,49.615988,50.384012,49.405,-0.021085,50.595,2.703027,69.542,67.485,71.69
136,Indonesia,2012,66.607676,5.117567,1.3517,49.615539,50.384461,48.724,-0.036292,51.276,2.688705,69.866,67.784,72.047
137,Indonesia,2013,66.770053,5.192082,1.340771,49.621626,50.378374,48.045,-0.062594,51.955,2.656286,70.179,68.081,72.383
138,Indonesia,2014,66.953568,5.278582,1.310945,49.62947,50.37053,47.365,-0.114506,52.635,2.611279,70.481,68.371,72.698
139,Indonesia,2015,67.165592,5.383435,1.26783,49.63573,50.36427,46.687,-0.173951,53.313,2.54772,70.768,68.651,72.992
140,Indonesia,2016,67.24298,5.524336,1.220591,49.639592,50.360408,46.011,-0.237934,53.989,2.480603,71.035,68.914,73.264
141,Indonesia,2017,67.40315,5.681948,1.176197,49.642056,50.357944,45.341,-0.290682,54.659,2.409554,71.282,69.156,73.515
142,Indonesia,2018,67.591637,5.857166,1.134507,49.643882,50.356118,44.675,-0.345257,55.325,2.345607,71.509,69.375,73.748
143,Indonesia,2019,67.734578,6.050303,1.097926,49.646383,50.353617,44.015,-0.390432,55.985,2.283818,71.716,69.572,73.967
144,Indonesia,2020,67.8014803219093,6.26251338481323,1.06517898587775,49.6504687615261,50.3495312384739,43.359,-0.436439683580507,56.641,2.23010935628228,..,..,..

Fill in Empty Cells

In [21]:

#Replace emply values with NaN
final_table['Life_Exp_Birth_Female_Yr'].replace({'..': np.NaN}, inplace = True)
final_table['Life_Exp_Birth_Male_Yr'].replace({'..': np.NaN}, inplace = True)
final_table['Life_Exp_Birth_Total_Yr'].replace({'..': np.NaN}, inplace = True)

#Replace NaN values with last observation
final_table.fillna(method="ffill", inplace=True)


display(final_table.head(20))

,Country,Year,Population_15To64_Percent,Population_65andUp_Percent,Population_Growth_Percent,Population_Female_Percent,Population_Male_Percent,Rural_Population_Percent,Rural_Population_Growth_Percent,Urban_Population_Percent,Urban_Population_Growth_Percent,Life_Exp_Birth_Total_Yr,Life_Exp_Birth_Male_Yr,Life_Exp_Birth_Female_Yr
0,Blank,0,Population ages 15-64 (% of total population),Population ages 65 and above (% of total popul...,Population growth (annual %),"Population, female (% of total population)","Population, male (% of total population)",Rural population (% of total population),Rural population growth (annual %),Urban population (% of total population),Urban population growth (annual %),"Life expectancy at birth, total (years)","Life expectancy at birth, male (years)","Life expectancy at birth, female (years)"
1,Canada,2005,69.206502,13.117552,0.944467,50.425044,49.574956,19.878,0.557844,80.122,1.040619,80.192683,77.9,82.6
2,Canada,2006,69.330341,13.268681,1.010335,50.415091,49.584909,19.787,0.551491,80.213,1.123847,80.343902,78.1,82.7
3,Canada,2007,69.427679,13.436645,0.971135,50.404456,49.595544,19.604,0.041978,80.396,1.199019,80.543902,78.3,82.9
4,Canada,2008,69.476335,13.631938,1.082907,50.394821,49.605179,19.422,0.150192,80.578,1.30903,80.695122,78.5,83.0
5,Canada,2009,69.455658,13.867931,1.141758,50.388411,49.611589,19.242,0.210657,80.758,1.364894,80.995122,78.8,83.3
6,Canada,2010,69.357773,14.153651,1.111864,50.386484,49.613516,19.063,0.177253,80.937,1.333269,81.246341,79.1,83.5
7,Canada,2011,69.133519,14.451218,0.978698,50.389737,49.610263,18.904,0.14113,81.096,1.174953,81.44878,79.4,83.6
8,Canada,2012,68.89938,14.803899,1.085817,50.397092,49.602908,18.863,0.868694,81.137,1.136362,81.64878,79.6,83.8
9,Canada,2013,68.630895,15.201846,1.056591,50.405809,49.594191,18.822,0.838999,81.178,1.10711,81.74878,79.7,83.9
10,Canada,2014,68.31509,15.623366,1.005338,50.412305,49.587695,18.782,0.792588,81.218,1.054601,81.8,79.8,83.9
11,Canada,2015,67.954884,16.053635,0.746339,50.414127,49.585873,18.741,0.527808,81.259,0.796808,81.9,79.9,84.0
12,Canada,2016,67.646956,16.45501,1.132349,50.410566,49.589434,18.7,0.913336,81.3,1.182792,81.9,79.9,84.0
13,Canada,2017,67.287472,16.842492,1.199682,50.402562,49.597438,18.65,0.931952,81.35,1.261162,81.9,79.9,84.0
14,Canada,2018,66.897742,17.232007,1.412548,50.39153,49.60847,18.589,1.084928,81.411,1.487506,82.04878,80.0,84.2
15,Canada,2019,66.506203,17.647897,1.415015,50.379516,49.620484,18.518,1.032338,81.482,1.502188,82.04878,80.0,84.2
16,Canada,2020,66.1203862397467,18.1043615051754,1.08959148655862,50.3680248057894,49.6319751942105,18.438,0.656644458992974,81.562,1.18772430444538,82.04878,80.0,84.2
17,USA,2005,66.807154,12.311711,0.921713,50.653802,49.346198,20.072,0.07339,79.928,1.135885,77.487805,75.0,80.1
18,USA,2006,66.801557,12.380916,0.964254,50.643896,49.356104,19.901,0.10867,80.099,1.177968,77.687805,75.2,80.3
19,USA,2007,66.838224,12.471868,0.951055,50.636785,49.363215,19.731,0.093157,80.269,1.163068,77.987805,75.5,80.6

Remove Original Labels

In [22]:
pop_data = final_table.drop(0)
pop_data.head(200)

,Country,Year,Population_15To64_Percent,Population_65andUp_Percent,Population_Growth_Percent,Population_Female_Percent,Population_Male_Percent,Rural_Population_Percent,Rural_Population_Growth_Percent,Urban_Population_Percent,Urban_Population_Growth_Percent,Life_Exp_Birth_Total_Yr,Life_Exp_Birth_Male_Yr,Life_Exp_Birth_Female_Yr
1,Canada,2005,69.206502,13.117552,0.944467,50.425044,49.574956,19.878,0.557844,80.122,1.040619,80.192683,77.9,82.6
2,Canada,2006,69.330341,13.268681,1.010335,50.415091,49.584909,19.787,0.551491,80.213,1.123847,80.343902,78.1,82.7
3,Canada,2007,69.427679,13.436645,0.971135,50.404456,49.595544,19.604,0.041978,80.396,1.199019,80.543902,78.3,82.9
4,Canada,2008,69.476335,13.631938,1.082907,50.394821,49.605179,19.422,0.150192,80.578,1.30903,80.695122,78.5,83.0
5,Canada,2009,69.455658,13.867931,1.141758,50.388411,49.611589,19.242,0.210657,80.758,1.364894,80.995122,78.8,83.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140,Indonesia,2016,67.24298,5.524336,1.220591,49.639592,50.360408,46.011,-0.237934,53.989,2.480603,71.035,68.914,73.264
141,Indonesia,2017,67.40315,5.681948,1.176197,49.642056,50.357944,45.341,-0.290682,54.659,2.409554,71.282,69.156,73.515
142,Indonesia,2018,67.591637,5.857166,1.134507,49.643882,50.356118,44.675,-0.345257,55.325,2.345607,71.509,69.375,73.748
143,Indonesia,2019,67.734578,6.050303,1.097926,49.646383,50.353617,44.015,-0.390432,55.985,2.283818,71.716,69.572,73.967
144,Indonesia,2020,67.8014803219093,6.26251338481323,1.06517898587775,49.6504687615261,50.3495312384739,43.359,-0.436439683580507,56.641,2.23010935628228,71.716,69.572,73.967

Generate CSV

In [23]:
final_table.to_csv("Population_Processed_Table.csv", index = False, header = True)